#! /bin/bash

profile=$1
warSuffix=""

if [ ! $1 ]; then
	profile="prod"
fi

if [ $profile = "test" ]; then
	warSuffix="_test"
fi

# 构建
mvn clean package -P $profile

# # 上传
scp ./priv_service/target/privilege.war root@www.scyok.com:/mnt/service/privilege${warSuffix}.war

# 远程执行
ssh root@www.scyok.com << remotessh
cd /mnt/service
rm -rf privilege${warSuffix}
service tomcat restart
exit
remotessh
